DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Unknown exception raised: "<type 'exceptions.IndexError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5307706f2afae1739_at_1422431280_182', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5307706f2afae1739_at_1422431280_182/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5307706f2afae1739_at_1422431280_182/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-194 HTTP/1.1" 200 None 
DEBUG: Sending data: key=SECINT, name="Security Intelligence Investigation" 
DEBUG: Opened new Jira issue: id=458216, summary="[Test-Key-Word] Create New Jira Issue (Critical)" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5307706f2afae1739_at_1422431340_188', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5307706f2afae1739_at_1422431340_188/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5307706f2afae1739_at_1422431340_188/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-195 HTTP/1.1" 200 None 
DEBUG: Sending data: key=SECINT, name="Security Intelligence Investigation" 
DEBUG: Opened new Jira issue: id=458218, summary="[Test-Key-Word] Create New Jira Issue (Critical)" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Alert)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Alert)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__awurster__secint__RMD5766a69eb7aa0ea6c_at_1422432180_248', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__awurster__secint__RMD5766a69eb7aa0ea6c_at_1422432180_248/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__awurster__secint__RMD5766a69eb7aa0ea6c_at_1422432180_248/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.KeyError'>" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-196 HTTP/1.1" 200 None 
DEBUG: Sending data: key=SECINT, name="Security Intelligence Investigation" 
DEBUG: Opened new Jira issue: id=458224, summary="[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Alert)" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Unknown exception raised: "<type 'exceptions.IndexError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.1', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.1/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.1/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.2', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.2/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.2/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.3', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.3/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.3/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.4', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.4/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.4/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.5', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.5/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.5/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.6', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.6/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.6/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Unknown exception raised: "<type 'exceptions.IndexError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422439560_106', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422439560_106/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422439560_106/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.8', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.8/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.8/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Unknown exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.9', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.9/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.9/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Exception value: "No JSON object could be decoded" 
DEBUG: Exception traceback: "<traceback object at 0x7f2416b66248>" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.10', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.10/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.10/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.ValueError'>" 
DEBUG: Exception value: "No JSON object could be decoded" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.11', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.11/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.11/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.12', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.12/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.12/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f9879507fc8> 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.13', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.13/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.13/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7fe019abc128> 
DEBUG: labels from parsing=Test-Key-Word, labels from defaults=['splunk', ' incident'] 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.15', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.15/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.15/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f22e0980128> 
DEBUG: labels from parsing=Test-Key-Word, labels from defaults=['splunk', ' incident'] 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f9e377c3fc8> 
DEBUG: labels from parsing=Test-Key-Word, labels from defaults=['splunk', ' incident'] 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.16', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.16/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.16/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7ff3694c1128> 
DEBUG: labels from parsing=Test-Key-Word, labels from defaults=['splunk', ' incident'] 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f4c8ba70fc8> 
DEBUG: labels from parsing=['Test', 'Key', 'Word'], labels from defaults=['splunk', 'incident'] 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f15af13bfc8> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.17', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.17/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.17/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f4821cd1128> 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7fdc69c1cfc8> 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.18', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.18/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.18/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f254c7aa128> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f622d6a2fc8> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.19', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.19/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.19/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f3ac7b2c128> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f65adc42fc8> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7fd4634fdf80> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f5632beef80> 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7fac4ea9ff80> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-198 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f27f59a0f80> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f9990c53f80> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-199 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.7/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f06b529df80> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-200 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458272 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422443280_300', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422443280_300/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422443280_300/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f4c9c7f40e0> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-201 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458273 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.20', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.20/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.20/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7ff7622f20e0> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-202 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458275 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', 'host=awurster', 'host=awurster', '[Test-Key-Word] Create New Jira Issue (Critical)', 'Saved Search [[Test-Key-Word] Create New Jira Issue (Critical)] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.21', '', '/opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.21/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/rt_scheduler__nobody__secint__RMD5307706f2afae1739_at_1422437866_11.21/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7ffb792d50e0> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-203 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458284 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458284 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "unsupported operand type(s) for +: 'dict' and 'str'" 
DEBUG: <traceback object at 0x7f2a20dac0e0> 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 502 1574 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Exception raised: "(<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x7fa5d6163dd0>)" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 502 1574 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Exception raised: "(<type 'exceptions.IOError'>, IOError(2, 'No such file or directory'), <traceback object at 0x7f33414fedd0>)" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 502 1574 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422498060_2365', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422498060_2365/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422498060_2365/results.csv.gz 
DEBUG: Exception raised: "(<type 'exceptions.TypeError'>, TypeError("unsupported operand type(s) for +: 'dict' and 'str'",), <traceback object at 0x7ffb28a508c0>)" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 502 1574 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Exception raised: "<type 'exceptions.IOError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 503 1574 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Exception raised: "<type 'exceptions.IOError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-204 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458650 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458650 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422498540_2380/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422498540_2380/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.TypeError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-205 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458653 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458653 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422498540_2380/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Exception raised: "<type 'exceptions.IOError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-206 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458655 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458655 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['bin/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422496260_2269', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499020_2410/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499020_2410/results.csv.gz 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-207 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458656 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458656 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499380_2430', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499380_2430/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499380_2430/results.csv.gz 
DEBUG: event_data={noformat}	['']
T
y
p
e
	['']
Feed Name
	['']
Threat Score
	['']
Atlassian Usage
	['']
Last Seen in Feed
	['']
c
o
u
n
t
	['']
__mv_Feed Entity
	['']
__mv_Type
	['']
__mv_Feed Name
	['']
__mv_Threat Score
	['']
__mv_Atlassian Usage
	['']
__mv_Last Seen in Feed
	['']
__mv_count
54.210.163.130
	['']
i
p
v
4
	['']
internal - test feed
	['']
0.5
	['']
www.atlassian.com AWS host
	['']
2015-01-27 21:23:50.043251
	['']
1
	['']
	['']
	['']
	['']
	['']
	['']
	['']
59.167.133.100
	['']
i
p
v
4
	['']
internal - test feed
	['']
0.5
	['']
Atlassian Sydney Office NAT
	['']
2015-01-27 21:23:50.039302
	['']
1
	['']
	['']
	['']
	['']
	['']
	['']
	['']
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-208 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458659 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458659 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499740_2443', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499740_2443/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422499740_2443/results.csv.gz 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'T')] 
DEBUG: [('Feed Entity', 'y')] 
DEBUG: [('Feed Entity', 'p')] 
DEBUG: [('Feed Entity', 'e')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'Feed Name')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'Threat Score')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'Atlassian Usage')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'Last Seen in Feed')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'c')] 
DEBUG: [('Feed Entity', 'o')] 
DEBUG: [('Feed Entity', 'u')] 
DEBUG: [('Feed Entity', 'n')] 
DEBUG: [('Feed Entity', 't')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '__mv_Feed Entity')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '__mv_Type')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '__mv_Feed Name')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '__mv_Threat Score')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '__mv_Atlassian Usage')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '__mv_Last Seen in Feed')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '__mv_count')] 
DEBUG: [('Feed Entity', '54.210.163.130')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'i')] 
DEBUG: [('Feed Entity', 'p')] 
DEBUG: [('Feed Entity', 'v')] 
DEBUG: [('Feed Entity', '4')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'internal - test feed')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '0.5')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'www.atlassian.com AWS host')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '2015-01-27 21:23:50.043251')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '1')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '59.167.133.100')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'i')] 
DEBUG: [('Feed Entity', 'p')] 
DEBUG: [('Feed Entity', 'v')] 
DEBUG: [('Feed Entity', '4')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'internal - test feed')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '0.5')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', 'Atlassian Sydney Office NAT')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '2015-01-27 21:23:50.039302')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', '1')] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: [('Feed Entity', ''), (None, [''])] 
DEBUG: event_data={noformat}	['']
T
y
p
e
	['']
Feed Name
	['']
Threat Score
	['']
Atlassian Usage
	['']
Last Seen in Feed
	['']
c
o
u
n
t
	['']
__mv_Feed Entity
	['']
__mv_Type
	['']
__mv_Feed Name
	['']
__mv_Threat Score
	['']
__mv_Atlassian Usage
	['']
__mv_Last Seen in Feed
	['']
__mv_count
54.210.163.130
	['']
i
p
v
4
	['']
internal - test feed
	['']
0.5
	['']
www.atlassian.com AWS host
	['']
2015-01-27 21:23:50.043251
	['']
1
	['']
	['']
	['']
	['']
	['']
	['']
	['']
59.167.133.100
	['']
i
p
v
4
	['']
internal - test feed
	['']
0.5
	['']
Atlassian Sydney Office NAT
	['']
2015-01-27 21:23:50.039302
	['']
1
	['']
	['']
	['']
	['']
	['']
	['']
	['']
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-209 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458678 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458678 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502680_2550', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502680_2550/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502680_2550/results.csv.gz 
DEBUG: [('__mv_count', ''), ('Atlassian Usage', 'www.atlassian.com AWS host'), ('count', '1'), ('__mv_Threat Score', ''), ('__mv_Feed Name', ''), ('__mv_Atlassian Usage', ''), ('__mv_Last Seen in Feed', ''), ('Threat Score', '0.5'), ('Type', 'ipv4'), ('Last Seen in Feed', '2015-01-27 21:23:50.043251'), ('__mv_Type', ''), ('Feed Name', 'internal - test feed'), ('Feed Entity', '54.210.163.130'), ('__mv_Feed Entity', '')] 
DEBUG: [('__mv_count', ''), ('Atlassian Usage', 'Atlassian Sydney Office NAT'), ('count', '1'), ('__mv_Threat Score', ''), ('__mv_Feed Name', ''), ('__mv_Atlassian Usage', ''), ('__mv_Last Seen in Feed', ''), ('Threat Score', '0.5'), ('Type', 'ipv4'), ('Last Seen in Feed', '2015-01-27 21:23:50.039302'), ('__mv_Type', ''), ('Feed Name', 'internal - test feed'), ('Feed Entity', '59.167.133.100'), ('__mv_Feed Entity', '')] 
DEBUG: event_data={noformat}	www.atlassian.com AWS host	1					0.5	ipv4	2015-01-27 21:23:50.043251		internal - test feed	54.210.163.130
	Atlassian Sydney Office NAT	1					0.5	ipv4	2015-01-27 21:23:50.039302		internal - test feed	59.167.133.100
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-210 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458709 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458709 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502740_2554', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502740_2554/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502740_2554/results.csv.gz 
DEBUG: [('Feed Entity', '54.210.163.130'), ('Type', 'ipv4'), ('__mv_Feed Entity', ''), ('Last Seen in Feed', '2015-01-27 21:23:50.043251'), ('__mv_Threat Score', ''), ('__mv_Type', ''), ('__mv_Atlassian Usage', ''), ('__mv_Feed Name', ''), ('Feed Name', 'internal - test feed'), ('Threat Score', '0.5'), ('__mv_Last Seen in Feed', ''), ('Atlassian Usage', 'www.atlassian.com AWS host'), ('__mv_count', ''), ('count', '1')] 
DEBUG: [('Feed Entity', '59.167.133.100'), ('Type', 'ipv4'), ('__mv_Feed Entity', ''), ('Last Seen in Feed', '2015-01-27 21:23:50.039302'), ('__mv_Threat Score', ''), ('__mv_Type', ''), ('__mv_Atlassian Usage', ''), ('__mv_Feed Name', ''), ('Feed Name', 'internal - test feed'), ('Threat Score', '0.5'), ('__mv_Last Seen in Feed', ''), ('Atlassian Usage', 'Atlassian Sydney Office NAT'), ('__mv_count', ''), ('count', '1')] 
DEBUG: event_data={noformat}54.210.163.130	ipv4		2015-01-27 21:23:50.043251					internal - test feed	0.5		www.atlassian.com AWS host		1
59.167.133.100	ipv4		2015-01-27 21:23:50.039302					internal - test feed	0.5		Atlassian Sydney Office NAT		1
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-211 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458712 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458712 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502800_2555', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502800_2555/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422502800_2555/results.csv.gz 
DEBUG: [('__mv_Atlassian Usage', ''), ('__mv_Type', ''), ('count', '1'), ('Last Seen in Feed', '2015-01-27 21:23:50.043251'), ('__mv_Feed Entity', ''), ('Type', 'ipv4'), ('__mv_Last Seen in Feed', ''), ('Feed Entity', '54.210.163.130'), ('Threat Score', '0.5'), ('__mv_Threat Score', ''), ('__mv_Feed Name', ''), ('Feed Name', 'internal - test feed'), ('Atlassian Usage', 'www.atlassian.com AWS host'), ('__mv_count', '')] 
DEBUG: [('__mv_Atlassian Usage', ''), ('__mv_Type', ''), ('count', '1'), ('Last Seen in Feed', '2015-01-27 21:23:50.039302'), ('__mv_Feed Entity', ''), ('Type', 'ipv4'), ('__mv_Last Seen in Feed', ''), ('Feed Entity', '59.167.133.100'), ('Threat Score', '0.5'), ('__mv_Threat Score', ''), ('__mv_Feed Name', ''), ('Feed Name', 'internal - test feed'), ('Atlassian Usage', 'Atlassian Sydney Office NAT'), ('__mv_count', '')] 
DEBUG: event_data={noformat}		1	2015-01-27 21:23:50.043251		ipv4		54.210.163.130	0.5			internal - test feed	www.atlassian.com AWS host
		1	2015-01-27 21:23:50.039302		ipv4		59.167.133.100	0.5			internal - test feed	Atlassian Sydney Office NAT
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-212 HTTP/1.1" 200 None 
DEBUG: "GET /jira/rest/api/2/issue/458713 HTTP/1.1" 200 None 
DEBUG: "PUT /jira/rest/api/2/issue/458713 HTTP/1.1" 400 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508680_2784', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508680_2784/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508680_2784/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-215 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422509340_2817', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422509340_2817/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422509340_2817/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-216 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-217 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422510660_2898', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422510660_2898/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422510660_2898/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-218 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: [('__mv_Feed Name', ''), ('Type', 'ipv4'), ('__mv_Feed Entity', ''), ('Threat Score', '0.5'), ('__mv_Type', ''), ('__mv_Atlassian Usage', ''), ('count', '1'), ('Feed Entity', '54.210.163.130'), ('__mv_Last Seen in Feed', ''), ('Atlassian Usage', 'www.atlassian.com AWS host'), ('__mv_Threat Score', ''), ('__mv_count', ''), ('Feed Name', 'internal - test feed'), ('Last Seen in Feed', '2015-01-27 21:23:50.043251')] 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-219 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422511320_2931', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422511320_2931/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422511320_2931/results.csv.gz 
DEBUG: [('Type', 'ipv4'), ('Last Seen in Feed', '2015-01-27 21:23:50.043251'), ('__mv_Feed Entity', ''), ('__mv_Type', ''), ('count', '1'), ('__mv_Atlassian Usage', ''), ('Atlassian Usage', 'www.atlassian.com AWS host'), ('__mv_Feed Name', ''), ('Feed Name', 'internal - test feed'), ('__mv_count', ''), ('Feed Entity', '54.210.163.130'), ('Threat Score', '0.5'), ('__mv_Threat Score', ''), ('__mv_Last Seen in Feed', '')] 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-220 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.KeyError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-221 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: event_data= 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-222 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: event_data= 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-223 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422511980_2963', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422511980_2963/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422511980_2963/results.csv.gz 
DEBUG: event_data= 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-224 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: event_data=		54.210.163.130	0.5			internal - test feed	www.atlassian.com AWS host		1	2015-01-27 21:23:50.043251		ipv4	
		59.167.133.100	0.5			internal - test feed	Atlassian Sydney Office NAT		1	2015-01-27 21:23:50.039302		ipv4	
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-225 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.NameError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-226 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: Exception raised: "<type 'exceptions.NameError'>" 
DEBUG: Exception value: "None" 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-227 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count0.5			1		54.210.163.130		ipv4		www.atlassian.com AWS host		internal - test feed	2015-01-27 21:23:50.043251	
0.5			1		59.167.133.100		ipv4		Atlassian Sydney Office NAT		internal - test feed	2015-01-27 21:23:50.039302	
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-228 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\\n  | lookup external_net Network AS entity OUTPUTNEW\\n  | lookup external_ip Host AS entity OUTPUTNEW\\n  | stats count by entity entity_type feed_name score Description last_seen\\n  | rename entity AS "Feed Entity" entity_type AS "Type" feed_name AS "Feed Name" score AS "Threat Score" Description AS "Atlassian Usage" last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422508020_2751/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
ipv4	2015-01-27 21:23:50.043251	internal - test feed		54.210.163.130	0.5			www.atlassian.com AWS host				1	
ipv4	2015-01-27 21:23:50.039302	internal - test feed		59.167.133.100	0.5			Atlassian Sydney Office NAT				1	
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-229 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422512640_3001', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422512640_3001/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422512640_3001/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
	www.atlassian.com AWS host			1		0.5		2015-01-27 21:23:50.043251	54.210.163.130	ipv4			internal - test feed
	Atlassian Sydney Office NAT			1		0.5		2015-01-27 21:23:50.039302	59.167.133.100	ipv4			internal - test feed
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-230 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422513300_3037', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422513300_3037/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422513300_3037/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
	ipv4	54.210.163.130		internal - test feed			www.atlassian.com AWS host	0.5		2015-01-27 21:23:50.043251		1	
	ipv4	59.167.133.100		internal - test feed			Atlassian Sydney Office NAT	0.5		2015-01-27 21:23:50.039302		1	
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-231 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422513960_3070', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422513960_3070/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422513960_3070/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
ipv4	internal - test feed	54.210.163.130			2015-01-27 21:23:50.043251				0.5		www.atlassian.com AWS host	1	
ipv4	internal - test feed	59.167.133.100			2015-01-27 21:23:50.039302				0.5		Atlassian Sydney Office NAT	1	
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-232 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422514620_3100', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422514620_3100/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422514620_3100/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
internal - test feed	1	ipv4		0.5					2015-01-27 21:23:50.043251	54.210.163.130	www.atlassian.com AWS host		
internal - test feed	1	ipv4		0.5					2015-01-27 21:23:50.039302	59.167.133.100	Atlassian Sydney Office NAT		
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-233 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422515280_3136', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422515280_3136/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422515280_3136/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
		internal - test feed			ipv4	54.210.163.130	1			2015-01-27 21:23:50.043251	0.5		www.atlassian.com AWS host
		internal - test feed			ipv4	59.167.133.100	1			2015-01-27 21:23:50.039302	0.5		Atlassian Sydney Office NAT
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-234 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422515880_3168', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422515880_3168/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422515880_3168/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
ipv4		www.atlassian.com AWS host		1	0.5	54.210.163.130	2015-01-27 21:23:50.043251				internal - test feed		
ipv4		Atlassian Sydney Office NAT		1	0.5	59.167.133.100	2015-01-27 21:23:50.039302				internal - test feed		
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-235 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422516540_3201', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422516540_3201/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422516540_3201/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
	internal - test feed	2015-01-27 21:23:50.043251	54.210.163.130		ipv4		www.atlassian.com AWS host			0.5			1
	internal - test feed	2015-01-27 21:23:50.039302	59.167.133.100		ipv4		Atlassian Sydney Office NAT			0.5			1
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-236 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '2', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '| inputlookup threatfeeder_net  | inputlookup threatfeeder_ip append=t\n  | lookup external_net Network AS entity OUTPUTNEW\n  | lookup external_ip Host AS entity OUTPUTNEW\n  | stats count by entity, entity_type, feed_name, score, Description, last_seen\n  | rename entity AS "Feed Entity", entity_type AS "Type", feed_name AS "Feed Name", score AS "Threat Score", Description AS "Atlassian Usage", last_seen AS "Last Seen in Feed"', '[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)', 'Saved Search [[PLAY-SECINT-FEED] Atlassian Address found in Blacklist (Low)] number of events(2)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/secint/@go?sid=scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422517140_3236', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422517140_3236/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__nobody__secint__RMD5295e5398e40565a2_at_1422517140_3236/results.csv.gz 
DEBUG: event_data=Feed Entity	Type	Feed Name	Threat Score	Atlassian Usage	Last Seen in Feed	count	__mv_Feed Entity	__mv_Type	__mv_Feed Name	__mv_Threat Score	__mv_Atlassian Usage	__mv_Last Seen in Feed	__mv_count
internal - test feed	1				0.5		ipv4		2015-01-27 21:23:50.043251			www.atlassian.com AWS host	54.210.163.130
internal - test feed	1				0.5		ipv4		2015-01-27 21:23:50.039302			Atlassian Sydney Office NAT	59.167.133.100
 
INFO: Starting new HTTPS connection (1): extranet.atlassian.com 
DEBUG: "POST /jira/rest/api/2/issue HTTP/1.1" 201 None 
DEBUG: "GET /jira/rest/api/2/issue/SECINT-237 HTTP/1.1" 200 None 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', 'DMC Alert - Total License Usage Near Daily Quota', 'Saved Search [DMC Alert - Total License Usage Near Daily Quota] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/splunk_management_console/@go?sid=scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423092780_1906', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423092780_1906/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423092780_1906/results.csv.gz 
DEBUG: event_data=Instance	License quota used (%)	License quota used (GB)	Total license quota (GB)	__mv_Instance	__mv_License quota used (%)	__mv_License quota used (GB)	__mv_Total license quota (GB)
	116.0	sp-search-sec-1		127.624		110.000	
 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', 'DMC Alert - Total License Usage Near Daily Quota', 'Saved Search [DMC Alert - Total License Usage Near Daily Quota] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/splunk_management_console/@go?sid=scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423108980_248', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423108980_248/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423108980_248/results.csv.gz 
DEBUG: event_data=Instance	License quota used (%)	License quota used (GB)	Total license quota (GB)	__mv_Instance	__mv_License quota used (%)	__mv_License quota used (GB)	__mv_Total license quota (GB)
sp-search-sec-1	121.6	182.332			150.000		
 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', 'DMC Alert - Total License Usage Near Daily Quota', 'Saved Search [DMC Alert - Total License Usage Near Daily Quota] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/splunk_management_console/@go?sid=scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423125180_985', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423125180_985/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423125180_985/results.csv.gz 
DEBUG: event_data=Instance	License quota used (%)	License quota used (GB)	Total license quota (GB)	__mv_Instance	__mv_License quota used (%)	__mv_License quota used (GB)	__mv_Total license quota (GB)
sp-search-sec-1	294.8	442.145					150.000
 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', 'DMC Alert - Total License Usage Near Daily Quota', 'Saved Search [DMC Alert - Total License Usage Near Daily Quota] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/splunk_management_console/@go?sid=scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423141380_1720', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423141380_1720/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423141380_1720/results.csv.gz 
DEBUG: event_data=Instance	License quota used (%)	License quota used (GB)	Total license quota (GB)	__mv_Instance	__mv_License quota used (%)	__mv_License quota used (GB)	__mv_Total license quota (GB)
150.000	671.587			sp-search-sec-1	447.7		
 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', 'DMC Alert - Total License Usage Near Daily Quota', 'Saved Search [DMC Alert - Total License Usage Near Daily Quota] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/splunk_management_console/@go?sid=scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423157580_2452', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423157580_2452/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423157580_2452/results.csv.gz 
DEBUG: event_data=Instance	License quota used (%)	License quota used (GB)	Total license quota (GB)	__mv_Instance	__mv_License quota used (%)	__mv_License quota used (GB)	__mv_Total license quota (GB)
	747.976			150.000	sp-search-sec-1	498.7	
 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', '| rest splunk_server_group=dmc_group_license_master /services/licenser/pools \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/groups | search is_active=1 | eval stack_id=stack_ids | fields splunk_server stack_id is_active] \n| search is_active=1 \n| fields splunk_server, stack_id, used_bytes \n| join type=outer stack_id splunk_server [rest splunk_server_group=dmc_group_license_master /services/licenser/stacks | eval stack_id=title | eval stack_quota=quota | fields splunk_server stack_id stack_quota] \n| stats sum(used_bytes) as used_bytes max(stack_quota) as stack_quota by splunk_server \n| eval usedGB=round(used_bytes/1024/1024/1024,3) \n| eval totalGB=round(stack_quota/1024/1024/1024,3) \n| eval percentage=round(usedGB / totalGB, 3)*100 \n| fields splunk_server, percentage, usedGB, totalGB \n| where percentage > 90 \n| rename splunk_server AS Instance, percentage AS "License quota used (%)", usedGB AS "License quota used (GB)", totalGB as "Total license quota (GB)"', 'DMC Alert - Total License Usage Near Daily Quota', 'Saved Search [DMC Alert - Total License Usage Near Daily Quota] number of events(1)', 'https://sp-search-sec-1.internal.atlassian.com:8443/app/splunk_management_console/@go?sid=scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423173780_3187', '', '/opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423173780_3187/results.csv.gz'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Opened raw search data from: /opt/splunk/var/run/splunk/dispatch/scheduler__admin_c3BsdW5rX21hbmFnZW1lbnRfY29uc29sZQ__RMD544e6bdae8b4cae07_at_1423173780_3187/results.csv.gz 
DEBUG: event_data=Instance	License quota used (%)	License quota used (GB)	Total license quota (GB)	__mv_Instance	__mv_License quota used (%)	__mv_License quota used (GB)	__mv_Total license quota (GB)
	754.258		sp-search-sec-1		150.000	502.8	
 
DEBUG: Jira Alerts executed with debugging enabled. 
DEBUG: Splunk script args list: ['/opt/splunk/bin/scripts/alert_to_jira.py', '1', '2', '3', '4', '5', '6', '7'] 
DEBUG: Opened connection to JIRA jira_user=secint_bot, jira_url=https://extranet.atlassian.com:443/jira 
DEBUG: Exception raised: "<type 'exceptions.IndexError'>" 
DEBUG: Exception value: "None" 
